"""Add password field

Revision ID: 564faaba5385
Revises: 9ab328e95a19
Create Date: 2025-03-03 08:05:18.629306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564faaba5385'
down_revision = '9ab328e95a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
